FROM python:3.12-slim

WORKDIR /opt/searxng

COPY searxng-master/requirements.txt searxng-master/requirements-server.txt ./
RUN pip install --no-cache-dir -r requirements.txt -r requirements-server.txt

COPY searxng-master/ ./
COPY searxng.settings.yml /etc/searxng/settings.yml

ENV SEARXNG_SETTINGS_PATH=/etc/searxng/settings.yml
EXPOSE 8080

CMD ["granian", "--interface", "wsgi", "--host", "0.0.0.0", "--port", "8080", "searx.webapp:app"]
